export enum ActivityType {
  addInvoice = "dodanie faktury",
  editInvoice = "edycja faktury",
  deleteInvoice = "usunięcie faktury",
}
export type AllDocumentsName = {
  AllDocumentsId: number;
  DocumentId: number;
  DocumentName: string ;
  MainTypeId: number | null;
  MainTypeName: string| null;
  TypeId: number | null;
  TypeName: string | null;
  SubtypeId: number | null;
  SubtypeName: string| null;
  Price: number;
  IsDeleted: 0 | 1;
} 

export type UserActivitiesType = {
  date: string;
  userName: string;
  activityType: ActivityType;
  activityData: string;
};
type FormattedDetail = {
  documentName: string;
  mainTypeName: string;
  typeName: string;
  subtypeName: string;
  quantity: number;
  price: string;
  total: string;
};

export type InvoiceTable = {
  InvoiceId?: number;
  InvoiceName: string;
  ReceiptDate: string;
  DeadlineDate: string | null;
  PaymentDate: string | null;
  IsDeleted: 0 | 1;
};
export type InvoiceDetailsTable = {
  InvoiceId?: number;
  DocumentId: number;
  MainTypeId: number | null;
  TypeId: number | null;
  SubtypeId: number | null;
  Quantity: number;
  Price: number;
  isMainTypeRequired?: boolean; // Nowe pole
  isTypeRequired?: boolean; // Nowe pole
  isSubtypeRequired?: boolean; // Nowe pole
};

export const UserActivities: UserActivitiesType = {
  date: "2025-07-22T11:30",
  userName: "Konrad",
  activityType: ActivityType.addInvoice,
  activityData: "",
};
export const addedInvoice = {
  InvoiceName: "FV/0713",
  ReceiptDate: "2025-07-14",
  DeadlineDate: null,
  PaymentDate: null,
  IsDeleted: 0,
} as InvoiceTable;

export const invoiceDetails = [
  {
    DocumentId: 3,
    MainTypeId: 1,
    TypeId: 1,
    SubtypeId: 1,
    Quantity: 1,
    Price: 3111,
    isMainTypeRequired: true,
    isTypeRequired: true,
    isSubtypeRequired: true,
  },
  {
    DocumentId: 1,
    MainTypeId: null,
    TypeId: null,
    SubtypeId: null,
    Quantity: 2,
    Price: 10,
    isMainTypeRequired: false,
    isTypeRequired: false,
    isSubtypeRequired: false,
  },
  {
    DocumentId: 4,
    MainTypeId: null,
    TypeId: null,
    SubtypeId: null,
    Quantity: 3,
    Price: 40,
    isMainTypeRequired: false,
    isTypeRequired: false,
    isSubtypeRequired: false,
  },
];

export const dataAllDocumentsName=[
  {
    AllDocumentsId: 41,
    DocumentId: 6,
    MainTypeId: 8,
    TypeId: null,
    SubtypeId: null,
    Price: 0.88,
    IsDeleted: 0,
    DocumentName: "DokumentTylkoMainType",
    MainTypeName: "TylkoMainType1",
    TypeName: null,
    SubtypeName: null,
  },
  {
    AllDocumentsId: 43,
    DocumentId: 7,
    MainTypeId: 6,
    TypeId: 7,
    SubtypeId: null,
    Price: 0.99,
    IsDeleted: 0,
    DocumentName: "DokumentTylkoType1",
    MainTypeName: "TylkoSubtype",
    TypeName: "TylkoType",
    SubtypeName: null,
  },
  {
    AllDocumentsId: 44,
    DocumentId: 7,
    MainTypeId: 7,
    TypeId: 6,
    SubtypeId: null,
    Price: 0.7,
    IsDeleted: 0,
    DocumentName: "DokumentTylkoType1",
    MainTypeName: "TylkoType",
    TypeName: "TylkoSubtype",
    SubtypeName: null,
  },
  {
    AllDocumentsId: 42,
    DocumentId: 7,
    MainTypeId: 7,
    TypeId: 7,
    SubtypeId: null,
    Price: 0.77,
    IsDeleted: 0,
    DocumentName: "DokumentTylkoType1",
    MainTypeName: "TylkoType",
    TypeName: "TylkoType",
    SubtypeName: null,
  },
  {
    AllDocumentsId: 37,
    DocumentId: 1,
    MainTypeId: null,
    TypeId: null,
    SubtypeId: null,
    Price: 10,
    IsDeleted: 0,
    DocumentName: "dowód rejestracyjny",
    MainTypeName: null,
    TypeName: null,
    SubtypeName: null,
  },
  {
    AllDocumentsId: 40,
    DocumentId: 5,
    MainTypeId: null,
    TypeId: null,
    SubtypeId: null,
    Price: 50,
    IsDeleted: 0,
    DocumentName: "KKK",
    MainTypeName: null,
    TypeName: null,
    SubtypeName: null,
  },
  {
    AllDocumentsId: 46,
    DocumentId: 10,
    MainTypeId: null,
    TypeId: null,
    SubtypeId: null,
    Price: 1,
    IsDeleted: 0,
    DocumentName: "nowy document prawo",
    MainTypeName: null,
    TypeName: null,
    SubtypeName: null,
  },
  {
    AllDocumentsId: 38,
    DocumentId: 2,
    MainTypeId: null,
    TypeId: null,
    SubtypeId: null,
    Price: 20,
    IsDeleted: 0,
    DocumentName: "pozwolenie czasowe",
    MainTypeName: null,
    TypeName: null,
    SubtypeName: null,
  },
  {
    AllDocumentsId: 39,
    DocumentId: 4,
    MainTypeId: null,
    TypeId: null,
    SubtypeId: null,
    Price: 40,
    IsDeleted: 0,
    DocumentName: "prawo jazdy",
    MainTypeName: null,
    TypeName: null,
    SubtypeName: null,
  },
  {
    AllDocumentsId: 35,
    DocumentId: 3,
    MainTypeId: 5,
    TypeId: 4,
    SubtypeId: 5,
    Price: 3545,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "dyplomatyczna",
    TypeName: "motocyklowa",
    SubtypeName: "niebieska",
  },
  {
    AllDocumentsId: 36,
    DocumentId: 3,
    MainTypeId: 5,
    TypeId: 5,
    SubtypeId: 5,
    Price: 3555,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "dyplomatyczna",
    TypeName: "motorowerowa",
    SubtypeName: "niebieska",
  },
  {
    AllDocumentsId: 33,
    DocumentId: 3,
    MainTypeId: 5,
    TypeId: 2,
    SubtypeId: 5,
    Price: 3525,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "dyplomatyczna",
    TypeName: "samochodowa dwurzędowa",
    SubtypeName: "niebieska",
  },
  {
    AllDocumentsId: 32,
    DocumentId: 3,
    MainTypeId: 5,
    TypeId: 1,
    SubtypeId: 5,
    Price: 3515,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "dyplomatyczna",
    TypeName: "samochodowa jednorzędowa",
    SubtypeName: "niebieska",
  },
  {
    AllDocumentsId: 34,
    DocumentId: 3,
    MainTypeId: 5,
    TypeId: 3,
    SubtypeId: 5,
    Price: 3535,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "dyplomatyczna",
    TypeName: "samochodowa jednorzędowa zmniejszona",
    SubtypeName: "niebieska",
  },
  {
    AllDocumentsId: 17,
    DocumentId: 3,
    MainTypeId: 2,
    TypeId: 4,
    SubtypeId: 1,
    Price: 3241,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "indywidualna",
    TypeName: "motocyklowa",
    SubtypeName: "biała",
  },
  {
    AllDocumentsId: 18,
    DocumentId: 3,
    MainTypeId: 2,
    TypeId: 4,
    SubtypeId: 2,
    Price: 3242,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "indywidualna",
    TypeName: "motocyklowa",
    SubtypeName: "zielona",
  },
  {
    AllDocumentsId: 13,
    DocumentId: 3,
    MainTypeId: 2,
    TypeId: 2,
    SubtypeId: 1,
    Price: 3221,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "indywidualna",
    TypeName: "samochodowa dwurzędowa",
    SubtypeName: "biała",
  },
  {
    AllDocumentsId: 14,
    DocumentId: 3,
    MainTypeId: 2,
    TypeId: 2,
    SubtypeId: 2,
    Price: 3222,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "indywidualna",
    TypeName: "samochodowa dwurzędowa",
    SubtypeName: "zielona",
  },
  {
    AllDocumentsId: 11,
    DocumentId: 3,
    MainTypeId: 2,
    TypeId: 1,
    SubtypeId: 1,
    Price: 3211,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "indywidualna",
    TypeName: "samochodowa jednorzędowa",
    SubtypeName: "biała",
  },
  {
    AllDocumentsId: 12,
    DocumentId: 3,
    MainTypeId: 2,
    TypeId: 1,
    SubtypeId: 2,
    Price: 3212,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "indywidualna",
    TypeName: "samochodowa jednorzędowa",
    SubtypeName: "zielona",
  },
  {
    AllDocumentsId: 15,
    DocumentId: 3,
    MainTypeId: 2,
    TypeId: 3,
    SubtypeId: 1,
    Price: 3231,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "indywidualna",
    TypeName: "samochodowa jednorzędowa zmniejszona",
    SubtypeName: "biała",
  },
  {
    AllDocumentsId: 16,
    DocumentId: 3,
    MainTypeId: 2,
    TypeId: 3,
    SubtypeId: 2,
    Price: 3232,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "indywidualna",
    TypeName: "samochodowa jednorzędowa zmniejszona",
    SubtypeName: "zielona",
  },
  {
    AllDocumentsId: 30,
    DocumentId: 3,
    MainTypeId: 4,
    TypeId: 4,
    SubtypeId: 3,
    Price: 3443,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "tymczasowa",
    TypeName: "motocyklowa",
    SubtypeName: "czerwona",
  },
  {
    AllDocumentsId: 31,
    DocumentId: 3,
    MainTypeId: 4,
    TypeId: 5,
    SubtypeId: 3,
    Price: 3453,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "tymczasowa",
    TypeName: "motorowerowa",
    SubtypeName: "czerwona",
  },
  {
    AllDocumentsId: 26,
    DocumentId: 3,
    MainTypeId: 4,
    TypeId: 2,
    SubtypeId: 3,
    Price: 3423,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "tymczasowa",
    TypeName: "samochodowa dwurzędowa",
    SubtypeName: "czerwona",
  },
  {
    AllDocumentsId: 27,
    DocumentId: 3,
    MainTypeId: 4,
    TypeId: 2,
    SubtypeId: 4,
    Price: 3424,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "tymczasowa",
    TypeName: "samochodowa dwurzędowa",
    SubtypeName: "żółta",
  },
  {
    AllDocumentsId: 24,
    DocumentId: 3,
    MainTypeId: 4,
    TypeId: 1,
    SubtypeId: 3,
    Price: 3413,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "tymczasowa",
    TypeName: "samochodowa jednorzędowa",
    SubtypeName: "czerwona",
  },
  {
    AllDocumentsId: 25,
    DocumentId: 3,
    MainTypeId: 4,
    TypeId: 1,
    SubtypeId: 4,
    Price: 3414,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "tymczasowa",
    TypeName: "samochodowa jednorzędowa",
    SubtypeName: "żółta",
  },
  {
    AllDocumentsId: 28,
    DocumentId: 3,
    MainTypeId: 4,
    TypeId: 3,
    SubtypeId: 3,
    Price: 3433,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "tymczasowa",
    TypeName: "samochodowa jednorzędowa zmniejszona",
    SubtypeName: "czerwona",
  },
  {
    AllDocumentsId: 29,
    DocumentId: 3,
    MainTypeId: 4,
    TypeId: 3,
    SubtypeId: 4,
    Price: 3434,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "tymczasowa",
    TypeName: "samochodowa jednorzędowa zmniejszona",
    SubtypeName: "żółta",
  },
  {
    AllDocumentsId: 22,
    DocumentId: 3,
    MainTypeId: 3,
    TypeId: 4,
    SubtypeId: 4,
    Price: 3344,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "zabytkowa",
    TypeName: "motocyklowa",
    SubtypeName: "żółta",
  },
  {
    AllDocumentsId: 23,
    DocumentId: 3,
    MainTypeId: 3,
    TypeId: 5,
    SubtypeId: 4,
    Price: 3354,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "zabytkowa",
    TypeName: "motorowerowa",
    SubtypeName: "żółta",
  },
  {
    AllDocumentsId: 20,
    DocumentId: 3,
    MainTypeId: 3,
    TypeId: 2,
    SubtypeId: 4,
    Price: 3324,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "zabytkowa",
    TypeName: "samochodowa dwurzędowa",
    SubtypeName: "żółta",
  },
  {
    AllDocumentsId: 19,
    DocumentId: 3,
    MainTypeId: 3,
    TypeId: 1,
    SubtypeId: 4,
    Price: 3314,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "zabytkowa",
    TypeName: "samochodowa jednorzędowa",
    SubtypeName: "żółta",
  },
  {
    AllDocumentsId: 21,
    DocumentId: 3,
    MainTypeId: 3,
    TypeId: 3,
    SubtypeId: 4,
    Price: 3334,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "zabytkowa",
    TypeName: "samochodowa jednorzędowa zmniejszona",
    SubtypeName: "żółta",
  },
  {
    AllDocumentsId: 7,
    DocumentId: 3,
    MainTypeId: 1,
    TypeId: 4,
    SubtypeId: 1,
    Price: 3141,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "zwyczajna",
    TypeName: "motocyklowa",
    SubtypeName: "biała",
  },
  {
    AllDocumentsId: 8,
    DocumentId: 3,
    MainTypeId: 1,
    TypeId: 4,
    SubtypeId: 2,
    Price: 3142,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "zwyczajna",
    TypeName: "motocyklowa",
    SubtypeName: "zielona",
  },
  {
    AllDocumentsId: 9,
    DocumentId: 3,
    MainTypeId: 1,
    TypeId: 5,
    SubtypeId: 1,
    Price: 3151,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "zwyczajna",
    TypeName: "motorowerowa",
    SubtypeName: "biała",
  },
  {
    AllDocumentsId: 10,
    DocumentId: 3,
    MainTypeId: 1,
    TypeId: 5,
    SubtypeId: 2,
    Price: 3152,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "zwyczajna",
    TypeName: "motorowerowa",
    SubtypeName: "zielona",
  },
  {
    AllDocumentsId: 3,
    DocumentId: 3,
    MainTypeId: 1,
    TypeId: 2,
    SubtypeId: 1,
    Price: 3121,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "zwyczajna",
    TypeName: "samochodowa dwurzędowa",
    SubtypeName: "biała",
  },
  {
    AllDocumentsId: 4,
    DocumentId: 3,
    MainTypeId: 1,
    TypeId: 2,
    SubtypeId: 2,
    Price: 3122,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "zwyczajna",
    TypeName: "samochodowa dwurzędowa",
    SubtypeName: "zielona",
  },
  {
    AllDocumentsId: 1,
    DocumentId: 3,
    MainTypeId: 1,
    TypeId: 1,
    SubtypeId: 1,
    Price: 3111,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "zwyczajna",
    TypeName: "samochodowa jednorzędowa",
    SubtypeName: "biała",
  },
  {
    AllDocumentsId: 2,
    DocumentId: 3,
    MainTypeId: 1,
    TypeId: 1,
    SubtypeId: 2,
    Price: 25.4,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "zwyczajna",
    TypeName: "samochodowa jednorzędowa",
    SubtypeName: "zielona",
  },
  {
    AllDocumentsId: 5,
    DocumentId: 3,
    MainTypeId: 1,
    TypeId: 3,
    SubtypeId: 1,
    Price: 3131,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "zwyczajna",
    TypeName: "samochodowa jednorzędowa zmniejszona",
    SubtypeName: "biała",
  },
  {
    AllDocumentsId: 6,
    DocumentId: 3,
    MainTypeId: 1,
    TypeId: 3,
    SubtypeId: 2,
    Price: 3132,
    IsDeleted: 0,
    DocumentName: "tablica rejestracyjna",
    MainTypeName: "zwyczajna",
    TypeName: "samochodowa jednorzędowa zmniejszona",
    SubtypeName: "zielona",
  },
] as AllDocumentsName[];